### ISSUE TITLE
Problems running the pipeline

### ISSUE THREAD

**Issue by alcazar90** [shreyashankar/toy-applied-ml-pipeline#65]
Hi @shreyashankar !

Thanks for sharing the project.

I want to understand the implementation to start contributing to the tasks open in the roadmap.
However, I have problems when I try to run the first component of the pipeline.

`docker run --env-file=./.env toy-ml-pipeline cleaning`

![image](https://user-images.githubusercontent.com/14035919/139073602-6074d509-e8ab-45b1-845a-c78fcffd7c70.png)

I am a newbie with docker; I built the image perfectly following the instructions.

![image](https://user-images.githubusercontent.com/14035919/139073349-e0b08e2c-e525-48ef-8d89-35244448bbb1.png)

The error message tells me that docker didn't find any `./.env` file when I ran the command `docker run --env-file`.

Reading [this blog post](https://vsupalov.com/docker-arg-env-variable-guide/), section _"3. Take values from a file (env_file)"_, the docker expects to find an `./.env` on the current directory. This file is created when the image is built? or it's supposed that it is in the repository?

Best,
Cristóbal

**Comment by shreyashankar** [comment]
Hi! Thanks for the detailed issue :) 

To run the pipeline end-to-end and contribute, you will need AWS permissions as described in [here](https://github.com/shreyashankar/toy-ml-pipeline#data-storage). You will need to create a `.env` file in your root directory with AWS keys. Email me at shreyashankar@berkeley.edu and I can set you up with keys :)
